//
//  TabbarInteractor.swift
//  VKOAuth2
//
//  Created by Admin on 10.09.2020.
//  Copyright (c) 2020 Danil Semenov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class TabbarInteractor {
}

// MARK: - Extensions -

extension TabbarInteractor: TabbarInteractorInterface {
}
