//
//  FriendsInterfaces.swift
//  VKOAuth2
//
//  Created by Admin on 10.09.2020.
//  Copyright (c) 2020 Danil Semenov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol FriendsWireframeInterface: WireframeInterface {
}

protocol FriendsViewInterface: ViewInterface {
    func onUpdate()
}

protocol FriendsPresenterInterface: PresenterInterface {
    var friends: [User] { get set }
    var friendsCount: Int { get }
    func viewDidLoad()
    func loadMoreFriends()
}

protocol FriendsInteractorInterface: InteractorInterface {
    func loadFriends(offset: Int, completion: @escaping ([User]) -> ())
}
