//
//  FriendsPresenter.swift
//  VKOAuth2
//
//  Created by Admin on 10.09.2020.
//  Copyright (c) 2020 Danil Semenov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FriendsPresenter {

    // MARK: - Private properties -

    private unowned let view: FriendsViewInterface
    private let interactor: FriendsInteractorInterface
    private let wireframe: FriendsWireframeInterface
    
    private var friendsArray: [User] = []

    // MARK: - Lifecycle -

    init(view: FriendsViewInterface, interactor: FriendsInteractorInterface, wireframe: FriendsWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension FriendsPresenter: FriendsPresenterInterface {
    var friends: [User] {
        get {
            friendsArray
        }
        set {
            self.friendsArray = newValue
        }
    }
    
    var friendsCount: Int {
        friends.count
    }
    
    func viewDidLoad() {
        interactor.loadFriends { [weak self] (users) in
            self?.friends.append(contentsOf: users)
            self?.view.onUpdate()
        }
    }
}
