//
//  LoginViewController.swift
//  VKOAuth2
//
//  Created by Admin on 02.09.2020.
//  Copyright (c) 2020 Danil Semenov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginViewController: UIViewController {

    // MARK: - Public properties -
    @IBOutlet weak var loginButton: UIButton!
    
    var presenter: LoginPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    // MARK: - Actions -
    @IBAction func tappedLogin(_ sender: Any) {
        self.presenter.tappedLogin()
    }
}

// MARK: - Extensions -

extension LoginViewController: LoginViewInterface {
    
}
