//
//  WebWireframe.swift
//  VKOAuth2
//
//  Created by Admin on 02.09.2020.
//  Copyright (c) 2020 Danil Semenov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class WebWireframe: BaseWireframe {

    // MARK: - Private properties -
    // MARK: - Module setup -

    init() {
        let moduleViewController = WebViewController()
        super.init(viewController: moduleViewController)

        let interactor = WebInteractor()
        let presenter = WebPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension WebWireframe: WebWireframeInterface {
    func popBack() {
        self.viewController.dismiss(animated: true)
    }
}
